name: cf-puppeteer
on: [push]

jobs:
  int_test_job:
    name: Run integration tests
    runs-on: ubuntu-latest
    steps:
      - name: Add CF Cli to apt-get
        run: |
          wget -q -O - https://packages.cloudfoundry.org/debian/cli.cloudfoundry.org.key | sudo apt-key add -
          echo "deb https://packages.cloudfoundry.org/debian stable main" | sudo tee /etc/apt/sources.list.d/cloudfoundry-cli.list
      - name: Install CF CLI
        run: |
          sudo apt-get update
          sudo apt-get install cf-cli
      - name: Checkout
        uses: actions/checkout@v2
      - name: compile plugin and install them
        run: |
          mkdir -p ./artifacts
          CGO_ENABLED=0 GOARCH=amd64 GOOS=linux go build -o ./artifacts/cf-puppeteer
          cf install-plugin -f ./artifacts/cf-puppeteer
          cf plugins
      - name: CF CLI Action
        uses: citizen-of-planet-earth/cf-cli-action@v1
        with:
          cf_api: ${{secrets.API_BM}}
          cf_username: ${{secrets.USER_NAME_BM}}
          cf_password: ${{secrets.PASSWORD_BM}}
          cf_org: ${{secrets.ORG_BM}}
          cf_space: "dev"
          command: plugins
