name: cf-puppeteer
on: [push]

jobs:
  int_test_job:
    name: Run integration tests
    runs-on: ubuntu-latest
    steps:
      - name: Add CF Cli to apt-get
        run: |
          wget -q -O - https://packages.cloudfoundry.org/debian/cli.cloudfoundry.org.key | sudo apt-key add -
          echo "deb https://packages.cloudfoundry.org/debian stable main" | sudo tee /etc/apt/sources.list.d/cloudfoundry-cli.list
      - name: Install CF CLI
        run: |
          sudo apt-get update
          sudo apt-get install cf-cli
      - name: Checkout
        uses: actions/checkout@v2
      - name: Compile plugin
        run: |
          mkdir -p ./artifacts
          CGO_ENABLED=0 GOARCH=amd64 GOOS=linux go build -o ./artifacts/cf-puppeteer
      - name: Install Puppeteer plugin
        run: |
          cf install-plugin -f ./artifacts/cf-puppeteer
          cf plugins
      - name: CF Login
        run: |
          cf login -a ${{ secrets.API_BM }} -u ${{secrets.USER_NAME_BM}} -p ${{secrets.PASSWORD_BM}} -o ${{secrets.ORG_BM}} -s dev
      - name: Deploy test application without routes
        run: |
          cf zero-downtime-push -f test/integration/manifest.yml -p test/integration --no-route --no-start--env foo=bar --venerable-action stop
      - name: Check deployment 1
        run: |
          echo "Add api tests to check the deployed settings"
      - name: Deploy add routes to application
        run: |
          cf zero-downtime-push -f test/integration/manifest.yml -p test/integration --route-only
      - name: Delete application
        run: |
          cf delete -f puppeteer
      - name: Deploy test application (legacy push)
        run: |
          cf zero-downtime-push -f test/integration/manifest.yml -p test/integration --no-route --no-start--env foo=bar --venerable-action stop --legacy-push
      - name: Delete application
        run: |
         cf delete -f puppeteer
