name: cf-puppeteer
on: [push]

jobs:
  int_test_job:
    name: Run integration tests
    runs-on: ubuntu-latest
    steps:
      - name: Add CF Cli to apt-get
        run: |
          wget -q -O - https://packages.cloudfoundry.org/debian/cli.cloudfoundry.org.key | sudo apt-key add -
          echo "deb https://packages.cloudfoundry.org/debian stable main" | sudo tee /etc/apt/sources.list.d/cloudfoundry-cli.list
      - name: Install CF CLI
        run: |
          sudo apt-get update
          sudo apt-get install cf-cli
      - name: Checkout
        uses: actions/checkout@v2
      - name: Compile plugin
        run: |
          mkdir -p ./artifacts
          CGO_ENABLED=0 GOARCH=amd64 GOOS=linux go build -o ./artifacts/cf-puppeteer
      - name: Install Puppeteer plugin
        run: |
          cf install-plugin -f ./artifacts/cf-puppeteer
          cf plugins
      - name: CF Login
        run: |
          cf login -a ${{ secrets.API_BM }} -u ${{secrets.USER_NAME_BM}} -p ${{secrets.PASSWORD_BM}} -o ${{secrets.ORG_BM}} -s dev
      - name: Deploy Application
        run: |
          echo "TODO"
